// export const ADD_GOODS = 'ADD_GOODS'
// export const UPDATE_GOODS = 'UPDATE_GOODS'
// export const DELETE_GOODS = 'DELETE_GOODS'

const ADD_GOODS = 'ADD_GOODS'
const UPDATE_GOODS = 'UPDATE_GOODS'
const DELETE_GOODS = 'DELETE_GOODS'

export {ADD_GOODS,UPDATE_GOODS,DELETE_GOODS}